/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package universidadg12.Vistas;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import universidadg12.Model.Alumno;
import universidadg12.Model.Inscripcion;
import universidadg12.Model.Materia;
import universidadg12.Persistencia.AlumnoData;
import universidadg12.Persistencia.InscripcionData;
import universidadg12.Persistencia.MateriaData;

/**
 *
 * @author patri
 */
public class ConsultarNota extends javax.swing.JInternalFrame {

    /**
     * Creates new form GestorInscripcion
     */
    public ConsultarNota() {
        initComponents();
        cargarCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblConsultarNota = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ComboAlumno = new javax.swing.JComboBox<>();
        btnConsultar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaInscripcion = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();

        lblConsultarNota.setText("Consultar Notas");

        jLabel2.setText("Alumno");

        ComboAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboAlumnoActionPerformed(evt);
            }
        });

        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        tablaInscripcion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Alumno", "Materia", "Nota"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaInscripcion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaInscripcionMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaInscripcion);

        jLabel4.setText("Visualice sus notas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblConsultarNota, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(189, 189, 189))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(btnConsultar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addGap(61, 61, 61))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel2)
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(ComboAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblConsultarNota, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ComboAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConsultar)
                    .addComponent(btnSalir))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed

        CargarTabla();
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void tablaInscripcionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaInscripcionMouseClicked

    }//GEN-LAST:event_tablaInscripcionMouseClicked

    private void ComboAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboAlumnoActionPerformed
        borrarFila();
    }//GEN-LAST:event_ComboAlumnoActionPerformed

    public void borrarFila() {
        DefaultTableModel modelo = (DefaultTableModel) tablaInscripcion.getModel();
        int indice = modelo.getRowCount() - 1;
        for (int i = indice; i >= 0; i--) {
            modelo.removeRow(i);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Alumno> ComboAlumno;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblConsultarNota;
    private javax.swing.JTable tablaInscripcion;
    // End of variables declaration//GEN-END:variables

    public void cargarCombo() {
        AlumnoData alumnoData = new AlumnoData();
        ArrayList<Alumno> listadoAlumnos = alumnoData.listarAlumnos();
        for (Alumno aux : listadoAlumnos) {
            ComboAlumno.addItem(aux);
        }

    }

    public void cargarComboMat() {
        MateriaData materiaData = new MateriaData();

        ArrayList<Materia> listadoMateria = materiaData.mostrarMaterias();
        for (Materia aux : listadoMateria) {

        }

    }

    public void CargarTabla() {
        DefaultTableModel modelo = (DefaultTableModel) tablaInscripcion.getModel();
        modelo.setRowCount(0);
        AlumnoData alumnoData = new AlumnoData();
        InscripcionData inscripcionData = new InscripcionData();

        Alumno alumnoCombo = (Alumno) ComboAlumno.getSelectedItem();
        Alumno alumno = alumnoData.buscarAlumnos(alumnoCombo.getDni());

        ArrayList<Inscripcion> listado = (ArrayList) inscripcionData.obtenerInscripcionesPorAlumno(alumno.getId_alumno());
        for (Inscripcion aux : listado) {

            String[] fila = {
                aux.getAlumno().toString(),
                aux.getMateria().toString(),
                String.valueOf(aux.getNota())

            };
            modelo.addRow(fila);
        }

    }

    public void CargarTablaInicio() {
        DefaultTableModel modelo = (DefaultTableModel) tablaInscripcion.getModel();
        modelo.setRowCount(0);
        AlumnoData alumnoData = new AlumnoData();
        InscripcionData inscripcionData = new InscripcionData();

        ArrayList<Inscripcion> listado = (ArrayList) inscripcionData.obtenerInscripciones();
        for (Inscripcion aux : listado) {

            String[] fila = {
                aux.getAlumno().toString(),
                aux.getMateria().toString(),
                String.valueOf(aux.getNota())

            };
            modelo.addRow(fila);
        }

    }
}
