/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package universidadg12.Vistas;

import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import universidadg12.Model.Alumno;
import universidadg12.Model.Inscripcion;
import universidadg12.Model.Materia;
import universidadg12.Persistencia.*;

/**
 *
 * @author Leandro
 */
public class GestorInscripcion extends javax.swing.JInternalFrame {

    private ArrayList<Alumno> listaA;
    private ArrayList<Materia> listaM;
    private DefaultTableModel modelo;

    private AlumnoData aData;
    private MateriaData mData;
    private InscripcionData insData;

    public GestorInscripcion() {
        initComponents();

        aData = new AlumnoData();
        insData = new InscripcionData();
        listaA = (ArrayList<Alumno>) aData.listarAlumnos();
        modelo = new DefaultTableModel();

        cargarAlumnos();
        armarCabecera();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rgbtnMaterias = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbAlumnos = new javax.swing.JComboBox<>();
        rbtnInscriptas = new javax.swing.JRadioButton();
        rbtnNoInscriptas = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMaterias = new javax.swing.JTable();
        btnInscribir = new javax.swing.JButton();
        btnAnularInscripcion = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Formulario de Inscripcion");

        jLabel2.setText("Alumno:");

        cmbAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAlumnosActionPerformed(evt);
            }
        });

        rgbtnMaterias.add(rbtnInscriptas);
        rbtnInscriptas.setSelected(true);
        rbtnInscriptas.setText("Inscriptas");
        rbtnInscriptas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnInscriptasActionPerformed(evt);
            }
        });

        rgbtnMaterias.add(rbtnNoInscriptas);
        rbtnNoInscriptas.setText("No Inscriptas");
        rbtnNoInscriptas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnNoInscriptasActionPerformed(evt);
            }
        });

        tblMaterias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblMaterias);

        btnInscribir.setText("Inscribir");
        btnInscribir.setEnabled(false);
        btnInscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInscribirActionPerformed(evt);
            }
        });

        btnAnularInscripcion.setText("Anular inscripcion");
        btnAnularInscripcion.setEnabled(false);
        btnAnularInscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnularInscripcionActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(cmbAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(rbtnInscriptas)
                        .addGap(18, 18, 18)
                        .addComponent(rbtnNoInscriptas))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btnInscribir)
                            .addGap(18, 18, 18)
                            .addComponent(btnAnularInscripcion)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSalir))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbtnInscriptas)
                    .addComponent(rbtnNoInscriptas))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInscribir)
                    .addComponent(btnAnularInscripcion)
                    .addComponent(btnSalir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void rbtnInscriptasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnInscriptasActionPerformed
        cargarInscriptas();
        btnAnularInscripcion.setEnabled(true);
        btnInscribir.setEnabled(false);
    }//GEN-LAST:event_rbtnInscriptasActionPerformed

    private void rbtnNoInscriptasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnNoInscriptasActionPerformed
        cargarNoInscriptas();
        btnInscribir.setEnabled(true);
        btnAnularInscripcion.setEnabled(false);
    }//GEN-LAST:event_rbtnNoInscriptasActionPerformed

    private void btnInscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInscribirActionPerformed
        int fila = tblMaterias.getSelectedRow();
        if (fila != -1) {
            Alumno a = (Alumno) cmbAlumnos.getSelectedItem();
            int id_materia = (Integer) modelo.getValueAt(fila, 0);
            String nombreMateria = (String) modelo.getValueAt(fila, 1);
            int anio = (Integer) modelo.getValueAt(fila, 2);
            Materia m = new Materia(id_materia, nombreMateria, anio, true);

            Inscripcion inscripcion = new Inscripcion(0, a, m);
            insData.guardarInscripcion(inscripcion);
            borrarFila();
            cargarNoInscriptas();

        }
    }//GEN-LAST:event_btnInscribirActionPerformed

    private void btnAnularInscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnularInscripcionActionPerformed
        int fila = tblMaterias.getSelectedRow();
        if (fila != -1) {
            Alumno a = (Alumno) cmbAlumnos.getSelectedItem();
            int id_alumno = a.getId_alumno();
            int id_materia = (Integer) modelo.getValueAt(fila, 0);

            insData.borrarInscripcion(id_alumno, id_materia);
            borrarFila();
            cargarInscriptas();
        }
    }//GEN-LAST:event_btnAnularInscripcionActionPerformed

    private void cmbAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAlumnosActionPerformed
        borrarFila();
        if(rbtnInscriptas.isSelected()) {
            cargarInscriptas();
        } else {
            cargarNoInscriptas();
        }
    }//GEN-LAST:event_cmbAlumnosActionPerformed

    public void cargarAlumnos() {
        for (Alumno aux : listaA) {
            cmbAlumnos.addItem(aux);
        }
    }

    public void armarCabecera() {
        ArrayList<Object> filaCabecera = new ArrayList<>();
        filaCabecera.add("ID");
        filaCabecera.add("Nombre");
        filaCabecera.add("Año");
        for (Object it : filaCabecera) {
            modelo.addColumn(it);
        }
        tblMaterias.setModel(modelo);
    }

    public void borrarFila() {
        int indice = modelo.getRowCount() - 1;

        for (int i = indice; i >= 0; i--) {
            modelo.removeRow(i);
        }
    }

    public void cargarNoInscriptas() {
        borrarFila();
        Alumno selec = (Alumno) cmbAlumnos.getSelectedItem();
        listaM = (ArrayList) insData.obtenerMateriasNoCursadas(selec.getId_alumno());
        for (Materia m : listaM) {
            modelo.addRow(new Object[]{m.getId_materia(), m.getNombre(), m.getAnio()});
        }
    }

    public void cargarInscriptas() {
        borrarFila();
        Alumno selec = (Alumno) cmbAlumnos.getSelectedItem();
        List<Materia> lista = insData.obtenerMateriasCursadas(selec.getId_alumno());
        for (Materia m : lista) {
            modelo.addRow(new Object[]{m.getId_materia(), m.getNombre(), m.getAnio()});
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnularInscripcion;
    private javax.swing.JButton btnInscribir;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<Alumno> cmbAlumnos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbtnInscriptas;
    private javax.swing.JRadioButton rbtnNoInscriptas;
    private javax.swing.ButtonGroup rgbtnMaterias;
    private javax.swing.JTable tblMaterias;
    // End of variables declaration//GEN-END:variables
}
